# Generated by Django 6.0 on 2026-01-11 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0010_alter_producto_precio_por_unidad_medida'),
        ('gestion_sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Alerta stock mínimo')),
                ('ubicacion_pasillo', models.CharField(blank=True, help_text='Ej: Pasillo 4, Góndola B', max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion_productos.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion_sucursales.sucursal')),
            ],
            options={
                'verbose_name': 'Stock de Producto',
                'verbose_name_plural': 'Stocks de Productos',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
    ]
