# Generated by Django 6.0 on 2026-01-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sucursales', '0003_alter_stock_ubicacion_pasillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ubicacion_pasillo',
            field=models.CharField(choices=[('ALM', 'Almacén'), ('BEB', 'Bebidas'), ('DEP', 'Deposito'), ('FRE', 'Frescos / Lácteos'), ('LIM', 'Limpieza'), ('PER', 'Perfumería')], default='ALM', max_length=3, verbose_name='Sector/Pasillo'),
        ),
    ]
