# Generated by Django 6.0 on 2026-01-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sucursales', '0005_movimientostock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.IntegerField(help_text='El sistema ajustará el signo automáticamente según el tipo.'),
        ),
    ]
