# Generated by Django 6.0 on 2026-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sucursales', '0007_alter_movimientostock_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('AJU', 'Ajuste (Rotura/Pérdida)'), ('ENT', 'Entrada (Compra/Proveedor)'), ('SAL', 'Salida (Venta/Despacho)'), ('WEB', 'Salida (Venta/Online)'), ('TRA', 'Transferencia entre sucursales')], max_length=20),
        ),
    ]
