# Generated by Django 6.0 on 2026-01-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='reemplazo_opcion',
            field=models.CharField(choices=[('No permitir reemplazos', 'No permitir reemplazos'), ('Llamado', 'Llamado telefónico'), ('Criterio de la Tienda', 'Criterio de la Tienda')], default='No permitir reemplazos', max_length=50, verbose_name='Criterio de Reemplazo'),
        ),
    ]
