# Generated by Django 6.0 on 2026-01-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0002_pedido_reemplazo_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
