# Generated by Django 6.0 on 2026-01-21 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0003_itempedido_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='canal',
            field=models.CharField(choices=[('WEB', 'Tienda Online'), ('MOS', 'Venta Mostrador')], default='WEB', max_length=3, verbose_name='Canal de Venta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor que atendió'),
        ),
    ]
