# Generated by Django 6.0 on 2026-01-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0004_pedido_canal_pedido_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta (Posnet)'), ('TRANSFERENCIA', 'Transferencia / QR')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nro_operacion_fiscal',
            field=models.CharField(blank=True, help_text='Nro de ticket o cupón', max_length=50, null=True),
        ),
    ]
