# Generated by Django 6.0 on 2026-01-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0005_pedido_forma_pago_pedido_nro_operacion_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia / QR')], default='EFECTIVO', max_length=20),
        ),
    ]
