# Generated by Django 6.0 on 2026-01-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('es_oferta', models.BooleanField(default=False, verbose_name='¿Es Oferta?')),
                ('es_novedad', models.BooleanField(default=False, verbose_name='¿Es Novedad?')),
                ('es_proximamente', models.BooleanField(default=False, verbose_name='¿Es Próximamente?')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
                ('tipo_envase', models.CharField(choices=[('BOT', 'Botella'), ('CAJ', 'Caja'), ('LATA', 'Lata'), ('BOL', 'Bolsa'), ('FRAS', 'Frasco'), ('UNI', 'Unidad/Suelto')], default='UNI', max_length=4)),
                ('descripcion_breve', models.CharField(max_length=255)),
                ('descripcion_detallada', models.TextField()),
                ('imagen_principal', models.ImageField(upload_to='productos/fotos/')),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('volumen_m3', models.DecimalField(decimal_places=4, default=0.0, help_text='Para calcular espacio en bodega', max_digits=6)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='gestion_productos.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='gestion_productos.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('es_actual', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='gestion_productos.producto')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
