# Generated by Django 6.0 on 2026-01-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_envase',
            field=models.CharField(choices=[('BOT', 'Botella'), ('CAJ', 'Caja'), ('LATA', 'Lata'), ('BOL', 'Bolsa'), ('FRAS', 'Frasco'), ('UNI', 'Unidad/Suelto'), ('PAQ', 'Paquete')], default='UNI', max_length=4),
        ),
    ]
