# Generated by Django 6.0 on 2026-01-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0002_alter_producto_tipo_envase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Para ordenar en el menú'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='gestion_productos.categoria', verbose_name='Categoría Superior (Padre)'),
        ),
        migrations.AddField(
            model_name='historialprecio',
            name='precio_regular',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='historialprecio',
            name='precio_sin_impuestos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='contenido_neto',
            field=models.CharField(blank=True, help_text='Ej: 500 gr, 1.5 Lts', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_sin_tacc',
            field=models.BooleanField(default=False, verbose_name='¿Es Sin TACC?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='etiqueta_descuento',
            field=models.CharField(blank=True, help_text='Ej: 25% DTO o 2x1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_por_unidad_medida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por Kilo/Litro', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='volumen_m3',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
    ]
