# Generated by Django 6.0 on 2026-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0003_alter_categoria_options_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_vegano',
            field=models.BooleanField(default=False, verbose_name='¿Es Vegano?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_vegetariano',
            field=models.BooleanField(default=False, verbose_name='¿Es Vegetariano?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='octogono_advertencia',
            field=models.CharField(blank=True, help_text='Ej: Exceso en Azúcares, Exceso en Sodio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_envase',
            field=models.CharField(choices=[('BAN', 'Bandeja'), ('BOL', 'Bolsa'), ('BOT', 'Botella'), ('BRIK', 'Tetrabrik'), ('CAJ', 'Caja'), ('FRAS', 'Frasco'), ('LATA', 'Lata'), ('UNI', 'Unidad/Suelto'), ('PAQ', 'Paquete'), ('SAC', 'Sachet')], default='UNI', max_length=4),
        ),
    ]
