# Generated by Django 6.0 on 2026-01-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0004_producto_es_vegano_producto_es_vegetariano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='volumen_m3',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
