# Generated by Django 6.0 on 2026-01-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0005_alter_producto_peso_kg_alter_producto_volumen_m3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_por_unidad_medida',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio por Kilo/Litro', max_digits=10, null=True),
        ),
    ]
