# Generated by Django 6.0 on 2026-01-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0006_alter_producto_precio_por_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
