# Generated by Django 6.0 on 2026-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0007_alter_producto_peso_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código SKU'),
        ),
    ]
