# Generated by Django 6.0 on 2026-01-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0009_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_por_unidad_medida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por Kilo/Litro', max_digits=10, null=True),
        ),
    ]
