# Generated by Django 6.0 on 2026-01-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0010_alter_producto_precio_por_unidad_medida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
