# Generated by Django 6.0 on 2026-01-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0011_alter_categoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('CM3', 'cm³'), ('LT', 'Litros'), ('UN', 'Unidad')], default='GR', max_length=3, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido_neto',
            field=models.CharField(blank=True, help_text='Ej: 500, 1.5', max_length=50),
        ),
    ]
