# Generated by Django 6.0 on 2026-01-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0012_producto_unidad_medida_alter_producto_contenido_neto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(choices=[(21.0, '21% (General)'), (10.5, '10.5% (Reducido)'), (0.0, '0% (Exento)')], decimal_places=2, default=21.0, max_digits=5, verbose_name='Porcentaje de IVA'),
        ),
    ]
