# Generated by Django 6.0 on 2026-01-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0013_producto_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict, help_text="Cargar en formato JSON. Ej: {'Dimensiones': {'Alto': '29cm'}, 'Potencia': '3000W'}", null=True, verbose_name='Especificaciones Técnicas'),
        ),
    ]
