# Generated by Django 6.0 on 2026-01-16 18:41

import gestion_productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0014_producto_especificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='especificaciones',
            field=models.JSONField(blank=True, default=gestion_productos.models.Producto.guia_especificaciones, help_text='Complete los valores entre comillas.', null=True, verbose_name='Especificaciones Técnicas'),
        ),
    ]
