# Generated by Django 6.0 on 2026-01-19 20:21

import gestion_productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0015_alter_producto_especificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_detallada',
            field=models.TextField(blank=True, default=gestion_productos.models.Producto.plantilla_descripcion_html, null=True, verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_envase',
            field=models.CharField(choices=[('BAN', 'Bandeja'), ('BOL', 'Bolsa'), ('BOT', 'Botella'), ('BRIK', 'Tetrabrik'), ('CAJ', 'Caja'), ('FRAS', 'Frasco'), ('LATA', 'Lata'), ('MAP', 'Maple'), ('UNI', 'Unidad/Suelto'), ('PAQ', 'Paquete'), ('SAC', 'Sachet')], default='UNI', max_length=4),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('CM3', 'cm³'), ('LT', 'Litros'), ('UN', 'Unidades')], default='GR', max_length=3, verbose_name='Unidad de Medida'),
        ),
    ]
