# Generated by Django 6.0 on 2026-01-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0016_alter_producto_descripcion_detallada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='precio_costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
