# Generated by Django 6.0 on 2026-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0018_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='contenido_neto',
            field=models.CharField(blank=True, help_text='Ej: 500, 1.5', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_envase',
            field=models.CharField(choices=[('BAN', 'Bandeja'), ('BOL', 'Bolsa'), ('BOT', 'Botella'), ('BRIK', 'Tetrabrik'), ('CAJ', 'Caja'), ('FRAS', 'Frasco'), ('LATA', 'Lata'), ('MAP', 'Maple'), ('UNI', 'Unidad/Suelto'), ('PAQ', 'Paquete'), ('SAC', 'Sachet')], default='UNI', max_length=4, verbose_name='Tipo de Envase'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('CM3', 'cm³'), ('LT', 'Litros'), ('UN', 'Unidades')], default='UN', max_length=3, verbose_name='Unidad de Medida'),
        ),
    ]
