# Generated by Django 6.0 on 2026-01-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0019_alter_producto_contenido_neto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True, help_text='Desmarcar para ocultar esta categoría y sus productos de la tienda.', verbose_name='¿Activa?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_envase',
            field=models.CharField(choices=[('AER', 'Bandeja'), ('BAN', 'Bandeja'), ('BOL', 'Bolsa'), ('BOT', 'Botella'), ('BRIK', 'Tetrabrik'), ('CAJ', 'Caja'), ('FRAS', 'Frasco'), ('LATA', 'Lata'), ('MAP', 'Maple'), ('UNI', 'Unidad/Suelto'), ('PAQ', 'Paquete'), ('SAC', 'Sachet')], default='UNI', max_length=4, verbose_name='Tipo de Envase'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('CM3', 'cm³'), ('ML', 'Ml'), ('LT', 'Litros'), ('UN', 'Unidades')], default='UN', max_length=3, verbose_name='Unidad de Medida'),
        ),
    ]
