# Generated by Django 6.0 on 2026-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0020_categoria_activa_alter_producto_tipo_envase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ahorrames',
            field=models.BooleanField(default=False, verbose_name='Ahorrames?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='exclusivo_online',
            field=models.BooleanField(default=False, verbose_name='Exclusivo Online'),
        ),
    ]
