# Generated by Django 6.0 on 2026-01-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SA', 'Super Administrador'), ('AS', 'Administrador de Sucursal'), ('VE', 'Vendedor'), ('CA', 'Cajera/o'), ('CL', 'Cliente')], default='CL', max_length=2),
        ),
    ]
