"""
Django settings for configuracion_principal project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SEGURIDAD
SECRET_KEY = config('SECRET_KEY', default='django-insecure-default-key-production')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Para Google
    'gestion_usuarios',
    'gestion_sucursales',
    'gestion_productos',
    'carrito',
    'gestion_pedidos',
    'gestion_interna',
    'ventas_mostrador',
    
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'configuracion_principal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                # Tu procesador personalizado va aquí abajo:
                'gestion_productos.context_processors.lista_categorias',
                'gestion_productos.context_processors.favoritos_usuario',
                'carrito.context_processor.importe_total_carrito', 
            ],
        },
    },
]

WSGI_APPLICATION = 'configuracion_principal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': config(
        'DATABASE_URL',
        default=f'postgresql://{config("DB_USER", default="postgres")}:{config("DB_PASSWORD", default="3382153AsD")}@{config("DB_HOST", default="127.0.0.1")}:{config("DB_PORT", default="5432")}/{config("DB_NAME", default="mi_ecommerce_db")}',
        cast=dj_database_url.parse
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # 1. Valida que no sea parecida al nombre o email
    # { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    
    # 2. Valida que tenga al menos 8 caracteres (esta es la más común de dejar)
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': { 'min_length': 4 } }, # Bajala a 4 si querés
    
    # 3. Valida que no sea una clave común (12345, password, etc)
    # { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    
    # 4. Valida que no sea solo números
    # { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'  # O 'es-es' según prefieras
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_L10N = True
USE_TZ = True
USE_THOUSAND_SEPARATOR = True  # <--- ESTA ES LA CLAVE
DECIMAL_SEPARATOR = ','        # Si querés coma para decimales
THOUSAND_SEPARATOR = '.'       # Punto para los miles

# Zona horaria de Buenos Aires


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Storage para WhiteNoise y Supabase Media
STORAGES = {
    "default": {
        "BACKEND": "configuracion_principal.storage_backends.MediaStorage" if not DEBUG else "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Especificar que usás un modelo de usuario personalizado
AUTH_USER_MODEL = 'gestion_usuarios.Usuario'
# Configuración para archivos multimedia (fotos de productos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Supabase S3 Configuration (for Production)
if not DEBUG:
    AWS_ACCESS_KEY_ID = config('SUPABASE_S3_ACCESS_KEY_ID', default='')
    AWS_SECRET_ACCESS_KEY = config('SUPABASE_S3_SECRET_ACCESS_KEY', default='')
    AWS_STORAGE_BUCKET_NAME = config('SUPABASE_S3_BUCKET_NAME', default='productos')
    AWS_S3_ENDPOINT_URL = config('SUPABASE_S3_ENDPOINT_URL', default='')
    AWS_S3_REGION_NAME = config('SUPABASE_S3_REGION_NAME', default='us-west-2')
    
    # Supabase S3 requires path-style addressing (forcePathStyle: true)
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    
    # Build the public URL for serving images from Supabase Storage
    # Supabase public URL: https://<project>.supabase.co/storage/v1/object/public/<bucket>/
    SUPABASE_PROJECT_REF = config('SUPABASE_PROJECT_REF', default='adrjdpdgcpcggnoxyegx')
    MEDIA_URL = f"https://{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}/"
# URLs de redirección
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# 1. Backends de autenticación (Necesario para Allauth)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 2. Configuración de Email para desarrollo
# Esto hace que los links de validación se vean en la consola de VS Code
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configuración de Robustez de Cuenta
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Se loguean con email
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none" # ¡Esto es lo que pediste! ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_USERNAME_REQUIRED = False        # No hace falta que inventen un username
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True # Evita errores de tipeo en registro
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True # Loguea automáticamente al validar
ACCOUNT_UNIQUE_EMAIL = True                # Un solo usuario por email
# Para q no se vea la ventana blanca fea de confirmacion
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True

#Configuracion apar el cliente de Correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='hrsossio71@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='pwfe hebt zooz wcnh') 
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Tu Tienda Online <hrsossio71@gmail.com>')

# Producción: CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = []
for host in ALLOWED_HOSTS:
    if host not in ["localhost", "127.0.0.1"]:
        if host == "*":
            # Si permitimos todo, no podemos poner "*" en CSRF facilmente, 
            # pero para testing en Render esto suele fallar si no ponemos el dominio real.
            pass
        else:
            CSRF_TRUSTED_ORIGINS.append(f"https://{host}")

# LOGGING para ver errores en Render
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'configuracion_principal.storage_backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'botocore': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
